# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('handle', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('last_tweet', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
